from __future__ import annotations
from typing import Protocol, Iterable, List, Optional
from dataclasses import dataclass, field

@dataclass
class Task:
    title: str
    description: str = ""
    status: str = "todo"
    id: Optional[int] = None   # assigned by store

@dataclass
class Project:
    name: str
    description: str = ""
    id: Optional[int] = None   # assigned by store
    tasks: List[Task] = field(default_factory=list)

class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: int) -> Project: ...
    def list(self) -> Iterable[Project]: ...
    def save(self, project: Project) -> None: ...
    def delete(self, project_id: int) -> None: ...

class TaskRepository(Protocol):
    def add(self, project_id: int, task: Task) -> Task: ...
    def get(self, project_id: int, task_id: int) -> Task: ...
    def list(self, project_id: int) -> Iterable[Task]: ...
    def save(self, project_id: int, task: Task) -> None: ...
    def delete(self, project_id: int, task_id: int) -> None: ...
